import { Navbar } from '@/components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bug Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{height:'100vh'}}>
        <Navbar />
        <main style={{height:'90%', padding: '0 1.25rem'}}>{children}</main>
      </body>
    </html>
  )
}
