FROM node:20-alpine

WORKDIR /app

ARG HOST
ARG USER
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG DATABASEPASSWORD
ARG DATABASENAME
ARG COOKIE_NAME
ARG COOKIE_KEY_TWO
ARG COOKIE_KEY_ONE

ENV HOST={$HOST}
ENV USER=${USER}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV DATABASEPASSWORD=${DATABASEPASSWORD}
ENV DATABASENAME=${DATABASENAME}
ENV COOKIE_NAME=${COOKIE_NAME}
ENV COOKIE_KEY_TWO=${COOKIE_KEY_TWO}
ENV COOKIE_KEY_ONE=${COOKIE_KEY_ONE}

COPY package.json ./

COPY backend/package.json backend/
RUN npm run install --omit=dev

COPY backend/ backend/

USER node

CMD [ "npm", "start", "--prefix", "backend" ]

EXPOSE 8000